name: Deploy Infrastructure with Terraform

on:
  push:
    paths:
      - 'infra/**'
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
      REGION: ${{ secrets.REGION }}
      BUCKET: ${{ secrets.BUCKET_NAME }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Terraform Init
        run: terraform -chdir=infra init

      - name: Terraform Plan
        run: |
          terraform -chdir=infra plan \
            -var="project_id=${{ secrets.PROJECT_ID }}" \
            -var="region=${{ secrets.REGION }}" \
            -var="bucket_name=${{ secrets.BUCKET_NAME }}" \
            -var="youtube_oauth_json=DUMMYSTRING" \
            -var="image_url=${{ secrets.IMAGE_URL }}"

      - name: Import existing resources if they exist
        run: |
          set -e
          cd infra
          IMPORT_FAILED=0
          terraform init \
          echo "Importing module.cloud_run.google_cloud_run_v2_service.service..."
          terraform state list | grep -q module.cloud_run.google_cloud_run_v2_service.service || \
          (gcloud run services describe image-processor --region="$REGION" --project="$PROJECT_ID" &>/dev/null && \
          terraform import module.cloud_run.google_cloud_run_v2_service.service "projects/$PROJECT_ID/locations/$REGION/services/image-processor") || IMPORT_FAILED=1

          echo "Importing module.scheduler.google_cloud_scheduler_job.job..."
          terraform state list | grep -q module.scheduler.google_cloud_scheduler_job.job || \
          (gcloud scheduler jobs describe fetch-and-process-images --location="$REGION" --project="$PROJECT_ID" &>/dev/null && \
          terraform import module.scheduler.google_cloud_scheduler_job.job "projects/$PROJECT_ID/locations/$REGION/jobs/fetch-and-process-images") || IMPORT_FAILED=1

          echo "Importing module.gcs.google_storage_bucket.media..."
          terraform state list | grep -q module.gcs.google_storage_bucket.media || \
          (gsutil ls -p "$PROJECT_ID" gs://$BUCKET &>/dev/null && \
          terraform import module.gcs.google_storage_bucket.media "$BUCKET") || IMPORT_FAILED=1

          echo "Finished importing. IMPORT_FAILED=$IMPORT_FAILED"
          echo "IMPORT_FAILED=$IMPORT_FAILED" >> $GITHUB_ENV

      - name: Terraform Apply
        if: env.IMPORT_FAILED == '0' && github.ref == 'refs/heads/main'
        run: |
          terraform -chdir=infra apply -auto-approve \
            -var="project_id=${{ secrets.PROJECT_ID }}" \
            -var="region=${{ secrets.REGION }}" \
            -var="bucket_name=${{ secrets.BUCKET_NAME }}" \
            -var="youtube_oauth_json=${{ secrets.YOUTUBE_OAUTH_JSON }}" \
            -var="image_url=${{ secrets.IMAGE_URL }}"

      - name: Skip apply due to failed imports
        if: env.IMPORT_FAILED != '0'
        run: echo "One or more resource imports failed. Skipping apply."
